name: Deploy to AWS
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
    steps:
      - name: checkout
        uses: action/checkout@v2
      - name: Clean install dependencies
        run: npm ci
